#!/usr/bin/env python3
"""
Quick setup script for Google Assistant quality voice features
Installs dependencies, configures API keys, and tests the system
"""

import os
import sys
import subprocess
import json
from pathlib import Path


def print_header(text):
    """Print formatted header"""
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}\n")


def print_step(number, text):
    """Print numbered step"""
    print(f"[{number}] {text}")


def run_command(cmd, description):
    """Run command and return success status"""
    print(f"  Running: {cmd}")
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        if result.returncode == 0:
            print(f"  ✅ {description}")
            return True
        else:
            print(f"  ❌ {description}")
            print(f"  Error: {result.stderr}")
            return False
    except Exception as e:
        print(f"  ❌ Error: {e}")
        return False


def install_dependencies():
    """Install required packages"""
    print_header("Step 1: Installing Dependencies")
    
    packages = {
        "Basic (Minimum)": [
            "edge-tts",
            "SpeechRecognition",
            "openai",
            "pyttsx3",
            "pyaudio",
            "playsound"
        ],
        "Audio Processing": [
            "numpy",
            "scipy",
            "librosa"
        ],
        "Optional (Offline TTS)": [
            "TTS"
        ]
    }
    
    for category, pkgs in packages.items():
        print(f"\n{category}:")
        for pkg in pkgs:
            run_command(
                f"pip install {pkg}",
                f"Installed {pkg}"
            )


def setup_api_keys():
    """Setup API keys"""
    print_header("Step 2: API Keys Configuration")
    
    print_step(1, "OpenAI Whisper API (Optional but Recommended)")
    print("  Get key from: https://platform.openai.com/api-keys")
    whisper_key = input("  Enter OpenAI API key (press Enter to skip): ").strip()
    
    print_step(2, "Google Cloud Credentials (Optional)")
    print("  Get credentials from: https://console.cloud.google.com")
    gcp_creds = input("  Enter path to GCP credentials JSON (press Enter to skip): ").strip()
    
    print_step(3, "Google Gemini API (Optional)")
    print("  Get key from: https://makersuite.google.com/app/apikey")
    gemini_key = input("  Enter Gemini API key (press Enter to skip): ").strip()
    
    # Save to .env file
    env_content = f"""# Google Assistant Voice System Configuration
# Generated by setup script

# OpenAI API Key for Whisper speech recognition
OPENAI_API_KEY={whisper_key if whisper_key else "your-key-here"}

# Google Cloud Credentials for Cloud Speech-to-Text
GOOGLE_APPLICATION_CREDENTIALS={gcp_creds if gcp_creds else "/path/to/credentials.json"}

# Google Gemini API for main AI responses
GEMINI_API_KEY={gemini_key if gemini_key else "your-key-here"}

# Audio Configuration
AUDIO_DEVICE_INDEX=0
SAMPLE_RATE=16000
CHUNK_SIZE=512

# Voice Preferences
DEFAULT_LANGUAGE=en
DEFAULT_VOICE_GENDER=female
DEFAULT_SPEAKING_STYLE=friendly

# System Settings
GPU_ACCELERATION=false
CACHE_AUDIO=true
CACHE_DIR=data/voice_cache
"""
    
    env_file = Path(".env")
    env_file.write_text(env_content)
    print(f"\n✅ Saved configuration to {env_file}")


def test_modules():
    """Test each module"""
    print_header("Step 3: Testing Modules")
    
    print_step(1, "Testing Neural Voice Engine")
    test_code = """
from modules.neural_voice_engine import get_neural_voice_engine
engine = get_neural_voice_engine()
print("✅ Neural Voice Engine loaded")
"""
    run_command(
        f'python -c "{test_code}"',
        "Neural Voice Engine"
    )
    
    print_step(2, "Testing Advanced Speech Recognizer")
    test_code = """
from modules.advanced_speech_recognizer import get_advanced_speech_recognizer
recognizer = get_advanced_speech_recognizer()
print("✅ Advanced Speech Recognizer loaded")
"""
    run_command(
        f'python -c "{test_code}"',
        "Advanced Speech Recognizer"
    )
    
    print_step(3, "Testing Wake Word Detector")
    test_code = """
from modules.wake_word_detector import get_wake_word_manager
manager = get_wake_word_manager()
print("✅ Wake Word Manager loaded")
"""
    run_command(
        f'python -c "{test_code}"',
        "Wake Word Manager"
    )
    
    print_step(4, "Testing Integration Module")
    test_code = """
from modules.google_assistant_voice_integration import get_voice_integration
integration = get_voice_integration()
print("✅ Voice Integration loaded")
"""
    run_command(
        f'python -c "{test_code}"',
        "Voice Integration Module"
    )


def create_example_app():
    """Create example application"""
    print_header("Step 4: Creating Example Application")
    
    example_code = '''"""
Example: Google Assistant Quality Voice Assistant
Demonstrates how to use the voice system in your app
"""

from modules.google_assistant_voice_integration import get_voice_integration, SpeakingStyle
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize voice system
voice = get_voice_integration()

# Set voice preferences
voice.set_voice_preferences(
    language="en",
    gender=voice.voice_engine.VoiceGender.FEMALE,
    style=SpeakingStyle.FRIENDLY
)

# Custom wake words
voice.set_wake_words([
    "hey assistant",
    "ok assistant",
    "yo assistant"
])

# Callback when wake word detected
def on_wake_detected(wake_word, confidence):
    print(f"🎤 Woke up with: {wake_word} ({confidence:.2%})")
    
    # Acknowledge
    voice.speak("I'm listening", style=SpeakingStyle.CHEERFUL)
    
    # Listen for command
    text, confidence = voice.listen(context="smart home control")
    
    if text:
        print(f"You said: {text}")
        
        # Here you would integrate with your AI (Gemini, etc)
        response = f"You said: {text}. Processing..."
        
        # Respond
        voice.speak(response, style=SpeakingStyle.FRIENDLY)

# Register callback
voice.on_wake_word_detected(on_wake_detected)

# Start the assistant
if __name__ == "__main__":
    print("🚀 Starting voice assistant...")
    print("🎤 Say 'hey assistant' to wake it up")
    
    voice.start_listening()
    
    try:
        while True:
            import time
            time.sleep(1)
    except KeyboardInterrupt:
        print("\\nStopping...")
        voice.stop_listening()
'''
    
    example_file = Path("example_voice_assistant.py")
    example_file.write_text(example_code)
    print(f"✅ Created example: {example_file}")


def print_summary():
    """Print setup summary"""
    print_header("Setup Complete! ✅")
    
    print("""
Your assistant now has Google Assistant quality voice features:

1. 📝 Neural TTS (Text-to-Speech)
   - Microsoft Neural Voices (Edge-TTS)
   - Multiple languages and emotions
   - Offline fallback (Coqui TTS)

2. 🎤 Advanced ASR (Speech Recognition)
   - OpenAI Whisper API (best accuracy)
   - Google Cloud Speech
   - Offline fallback (Vosk)

3. 🎯 Wake Word Detection
   - Always-on listening
   - Local, instant detection
   - Custom wake words

Usage:
------
1. Review GOOGLE_ASSISTANT_VOICE_GUIDE.md for detailed documentation
2. Run example_voice_assistant.py to test
3. Integrate into your main app.py using modules

Quick Integration:
------------------
from modules.google_assistant_voice_integration import get_voice_integration

voice = get_voice_integration()
voice.speak("Hello!")
text, confidence = voice.listen()
voice.start_listening()  # Always-on mode

Configuration:
---------------
Edit .env file to set API keys and preferences

Support:
--------
- Check logs in logs/ directory
- Test individual modules with test scripts
- Review documentation in docs/ directory

Next Steps:
-----------
1. ✅ Install dependencies
2. ✅ Configure API keys
3. ✅ Test modules
4. ⬜ Integrate into main app.py
5. ⬜ Fine-tune for your use case

Happy coding! 🚀
    """)


def main():
    """Main setup flow"""
    print_header("Google Assistant Quality Voice System Setup")
    
    print("""
This script will:
1. Install required Python packages
2. Configure API keys
3. Test all modules
4. Create example code

Let's get started!
    """)
    
    # Step 1: Install dependencies
    print("\nInstall dependencies? (y/n): ", end="")
    if input().lower() == 'y':
        install_dependencies()
    
    # Step 2: Setup API keys
    print("\nSetup API keys? (y/n): ", end="")
    if input().lower() == 'y':
        setup_api_keys()
    
    # Step 3: Test modules
    print("\nTest modules? (y/n): ", end="")
    if input().lower() == 'y':
        test_modules()
    
    # Step 4: Create example
    print("\nCreate example app? (y/n): ", end="")
    if input().lower() == 'y':
        create_example_app()
    
    # Summary
    print_summary()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Setup error: {e}")
        sys.exit(1)
